const iconViewerOptions = [
  {
    name: 'name',
    value: 'plus',
    type: [
      'plus',
      'exclamation',
      'exclamation-triangle',
      'arrow-down',
      'arrow-left',
      'arrow-right',
      'arrow-up',
      'sort',
      'calendar',
      'times',
      'caret-down',
      'caret-up',
      'check',
      'chevron-down',
      'chevron-left',
      'chevron-right',
      'chevron-up',
      'times-circle',
      'chevron-circle-down',
      'chevron-circle-left',
      'chevron-circle-right',
      'chevron-circle-up',
      'plus-circle',
      'commenting',
      'trash',
      'ban',
      'clone',
      'code',
      'download',
      'upload',
      'external-link',
      'question-circle',
      'ellipsis-h',
      'file-text',
      'print',
      'retweet',
      'search',
      'minus',
      'eye',
      'angle-down',
    ],
    description: 'Name of the icon',
  },
  {
    name: 'color',
    value: 'ink',
    type: [
      'ink',
      'inkLight',
      'negative',
      'positive',
      'purple',
      'white',
    ],
    description: 'Change the color',
  },
];

export default iconViewerOptions;
